version: '3'
services:
  app1:
    restart: always
    image: app_1:1.0
    expose:
      - "5000"
    environment:
      APP_NAME: "application 1"
  app2:
    restart: always
    image: app_1:1.0
    expose:
      - "5000"
    environment:
      APP_NAME: "application 2"

  nginx:
    restart: always
    image: my_nginx:1.0
    ports:
      - 8082:80
    links:
      - app1:app1
      - app2:app2